---
#descriptive value of the project
- name: deploy jupiter website
  hosts: all  # all server 
  become: yes   # alow ansible to change root user 
  become_user: root

  tasks:
    - name: update ec2 instance #name of the task 
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: change directory to the html directory
      shell: cd /var/www/html      # jupiter-main/* to cd /var/www/html

    - name: download web files from github
      get_url: 
       # url: https://github.com/Stephanthedevops/jupiter.git    if it is .zip file 
        url: httpd://github.com/azeezsalu/jupiter/archive/ref/heads/main.zip 
        dest: cd /var/www/html/ # we will download the web files into our html directory 

    - name: unzip the zip folder
      ansible.builtin.unarchive:
        src: /var/www/html/jupiter-main.zip
        dest: /var/www/html/
        remote_src: yes # Instance is remote so 

    - name: copy webfiles from the jupiter-main directory to the html directory
      copy: 
        src: /var/www/html/jupiter-main/
        dest: /var/www/html/
        remote_src: 

    - name: remove the jupiter-main directory
      file: 
        path: /var/www/html/jupiter-main # make shure you don't enter the forwars slash /
        state: absent #to delete 

    - name: remove the jupiter-main.zip folder
      file: 
        path: /var/www/html/jupiter-main.zip
        state: absent

    - name: start apache server, if not started
      ansible.builtin.service:
        enabled: yes
        name: httpd
        state: started